pipeline:
  build:
    image: eclogue/courser:dev
    commands:
      - composer install
      - composer run-script phpcs
      - composer run-script test
    when:
      branch:
        include: [ master, develop ]
        exclude: [ feature/* ]
  slack:
    image: plugins/slack
    channel: courser
    webhook: https://hooks.slack.com/services/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
    when:
     status: [ success, failure ]
